-- Seed the customer-claimed 5% popup offer. The browser presents this once,
-- carries the code through authoritative checkout, and marks it redeemed after
-- a completed order. Existing usage is preserved across idempotent updates.
INSERT INTO discount_codes (
  code,
  name,
  description,
  method,
  type,
  value,
  status,
  starts_at,
  ends_at,
  usage_limit,
  usage_count,
  priority,
  minimum_quantity,
  minimum_subtotal_cents,
  banner_text,
  terms,
  rules,
  created_at,
  updated_at
)
VALUES (
  'CLAIM5',
  'Claim 5% Off',
  'One claimed 5% discount on every item in the customer''s next order.',
  'code',
  'percentage',
  5,
  'active',
  NULL,
  NULL,
  NULL,
  0,
  0,
  1,
  NULL,
  'Claim 5% off every item in your next order',
  'Claim once. Applies to all items in one order. Automatic free shipping can still apply.',
  '[]'::jsonb,
  now(),
  now()
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  method = EXCLUDED.method,
  type = EXCLUDED.type,
  value = EXCLUDED.value,
  status = EXCLUDED.status,
  starts_at = EXCLUDED.starts_at,
  ends_at = EXCLUDED.ends_at,
  usage_limit = EXCLUDED.usage_limit,
  priority = EXCLUDED.priority,
  minimum_quantity = EXCLUDED.minimum_quantity,
  minimum_subtotal_cents = EXCLUDED.minimum_subtotal_cents,
  banner_text = EXCLUDED.banner_text,
  terms = EXCLUDED.terms,
  rules = EXCLUDED.rules,
  updated_at = now();
