import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';

test('admin products page exposes phase 1 filters and sort controls', async () => {
  const source = await readFile(path.join(import.meta.dirname, '..', 'src', 'admin', 'Products.jsx'), 'utf8');

  assert.match(source, /useAdminCollections/);
  assert.match(source, /CATEGORY_FILTERS/);
  assert.match(source, /VENDOR_FILTERS/);
  assert.match(source, /SORT_OPTIONS/);
  assert.match(source, /collection/);
  assert.match(source, /category/);
  assert.match(source, /vendor/);
  assert.match(source, /sort/);
  assert.match(source, /params\.set\('collection', collection\)/);
  assert.match(source, /params\.set\('category', category\)/);
  assert.match(source, /params\.set\('vendor', vendor\)/);
  assert.match(source, /params\.set\('sort', sort\)/);
  assert.match(source, /PRODUCT_VIEWS/);
  assert.match(source, /selectedProducts/);
  assert.match(source, /toggleProductSelection/);
  assert.match(source, /toggleAllProducts/);
  assert.match(source, /selectedProducts\.size/);
  assert.match(source, /More actions/);
  assert.match(source, /Export/);
  assert.match(source, /Import/);
  assert.match(source, /ProductImportDialog/);
  assert.match(source, /AdminActionMenu/);
  assert.match(source, /AdminConfirmDialog/);
  assert.match(source, /duplicateProduct/);
  assert.match(source, /confirmArchive/);
  assert.match(source, /bulkAction/);
  assert.match(source, /Export CSV/);
  assert.match(source, /pagination/);
  assert.match(source, /Product status/);
  assert.match(source, /Product organization/);
  assert.match(source, /Sales channels/);
  assert.match(source, /statusBadgeClass/);
  assert.match(source, /inventoryBadgeClass/);
  assert.match(source, /product-view-tabs/);
  assert.match(source, /product-filter-toolbar/);
  assert.match(source, /product-search-field/);
  assert.match(source, /SearchIcon/);
  assert.match(source, /Product filters/);
});

test('admin product editor exposes organization fields, variant price, and total inventory', async () => {
  const source = await readFile(path.join(import.meta.dirname, '..', 'src', 'admin', 'ProductEditor.jsx'), 'utf8');
  const collectionDropdown = await readFile(path.join(import.meta.dirname, '..', 'src', 'admin', 'CollectionDropdown.jsx'), 'utf8');
  const queuedProductMedia = await readFile(path.join(import.meta.dirname, '..', 'src', 'admin', 'QueuedProductMedia.jsx'), 'utf8');
  const newProductMedia = await readFile(path.join(import.meta.dirname, '..', 'src', 'admin', 'newProductMedia.js'), 'utf8');
  const nginx = await readFile(path.join(import.meta.dirname, '..', 'nginx.conf'), 'utf8');

  assert.match(source, /product-editor-shell/);
  assert.match(source, /product-editor-grid/);
  assert.match(source, /description-toolbar/);
  assert.match(source, /richStyleForCommand/);
  assert.match(source, /formatDescription/);
  assert.match(source, /Description toolbar/);
  assert.match(source, /contentEditable/);
  assert.match(source, /descriptionEditorRef/);
  assert.match(source, /syncDescriptionFromEditor/);
  assert.match(source, /applyRichDescriptionStyle/);
  assert.match(source, /Font style/);
  assert.match(source, /Font size/);
  assert.match(source, /Font color/);
  assert.match(source, /Font weight/);
  assert.match(source, /DESCRIPTION_FONT_STYLES/);
  assert.match(source, /DESCRIPTION_FONT_SIZES/);
  assert.match(source, /DESCRIPTION_COLORS/);
  assert.match(source, /DESCRIPTION_FONT_WEIGHTS/);
  assert.match(source, /Bold/);
  assert.match(source, /Italic/);
  assert.match(source, /Underline/);
  assert.match(source, /Heading/);
  assert.match(source, /Bullet list/);
  assert.match(source, /Link/);
  assert.match(source, /Media/);
  assert.match(source, /Add photos/);
  assert.match(source, /Remove photo/);
  assert.match(source, /Publishing/);
  assert.doesNotMatch(source, /Sales past 90 days/);
  assert.doesNotMatch(source, /₱0\.00 net sales/);
  assert.match(source, /category/);
  assert.match(source, /productType/);
  assert.match(source, /vendor/);
  assert.match(source, /tags/);
  assert.match(source, /themeTemplate/);
  assert.match(source, /Total inventory/);
  assert.match(source, /variantPricePeso/);
  assert.match(source, /priceCents:\s*pesoToCents\(variantPricePeso/);
  assert.match(source, /Product page content/);
  assert.match(source, /Product details/);
  assert.match(source, /Shipping/);
  assert.match(source, /Size Chart/);
  assert.match(source, /Width/);
  assert.match(source, /Length/);
  assert.match(source, /Sleeve length/);
  assert.match(source, /Shoulder drop length/);
  assert.match(source, /updateProductPage/);
  assert.match(source, /updateSizeChartRow/);
  assert.match(source, /addSizeChartRow/);
  assert.match(source, /removeSizeChartRow/);
  assert.match(source, /sizeChartRowIsComplete/);
  assert.match(source, /Complete every size chart field before saving/);
  assert.match(source, /AdminConfirmDialog/);
  assert.match(source, /restoreProduct/);
  assert.match(source, /Product duplicated as a draft with zero stock and missing Pancake mapping/);
  assert.match(source, /queuedImages/);
  assert.match(source, /queueNewProductImages/);
  assert.match(source, /removeQueuedImage/);
  assert.match(source, /buildNewProductBody/);
  assert.match(newProductMedia, /Add at least one product photo/);
  assert.doesNotMatch(source, /Save this product before uploading photos/);
  assert.match(source, /<CollectionDropdown/);
  assert.doesNotMatch(source, /COLLECTIONS\.map\(\(collection\)/);
  assert.match(collectionDropdown, /aria-haspopup="listbox"/);
  assert.match(collectionDropdown, /aria-multiselectable="true"/);
  assert.match(collectionDropdown, /useAdminCollections/);
  assert.match(collectionDropdown, /event\.key === 'Escape'/);
  assert.match(source, /<QueuedProductMedia/);
  assert.match(source, /reorderQueuedProductImages/);
  assert.match(source, /moveQueuedProductImage/);
  assert.match(queuedProductMedia, /Select up to 8 photos at once/);
  assert.match(queuedProductMedia, /PRODUCT_IMAGE_ACCEPT/);
  assert.match(source, /PRODUCT_IMAGE_ACCEPT/);
  assert.match(newProductMedia, /image\/jpeg,image\/png,image\/webp,image\/gif,image\/avif,image\/tiff/);
  assert.match(nginx, /client_max_body_size 350m;/);
  assert.match(queuedProductMedia, /multiple/);
  assert.match(queuedProductMedia, /draggable/);
  assert.match(queuedProductMedia, /onDragStart/);
  assert.match(queuedProductMedia, /onDrop/);
  assert.match(queuedProductMedia, /Move first/);
  assert.match(queuedProductMedia, /Move left/);
  assert.match(queuedProductMedia, /Move right/);
  assert.match(queuedProductMedia, /Move last/);
  assert.match(queuedProductMedia, /Storefront cover/);
  assert.match(source, /status:\s*'active'/);
  assert.match(source, /validateNewProduct/);
  assert.match(source, /fieldErrors/);
  assert.match(newProductMedia, /Enter a product title/);
  assert.match(newProductMedia, /Enter a price greater than zero/);
  assert.match(newProductMedia, /Select at least one storefront collection/);
  assert.match(newProductMedia, /Enter inventory before publishing an active product/);
});

test('storefront product page renders editable product page content and size chart rows', async () => {
  const source = await readFile(path.join(import.meta.dirname, '..', 'src', 'pages', 'Product.jsx'), 'utf8');

  assert.match(source, /productPage\.detailsText/);
  assert.match(source, /productPage\.shippingText/);
  assert.match(source, /productPage\.sizeChart/);
  assert.match(source, /sizeChartRows/);
  assert.match(source, /Shoulder drop/);
  assert.match(source, /sleeveLength/);
  assert.match(source, /shoulderDropLength/);
  assert.match(source, /visibleSections/);
  assert.match(source, /sectionTitle === 'product details'/);
  assert.match(source, /sectionTitle !== 'shipping'/);
  assert.match(source, /sectionTitle !== 'size chart'/);
});
