import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';

test('admin products page exposes phase 1 filters and sort controls', async () => {
  const source = await readFile(path.join(import.meta.dirname, '..', 'src', 'admin', 'Products.jsx'), 'utf8');

  assert.match(source, /COLLECTION_FILTERS/);
  assert.match(source, /CATEGORY_FILTERS/);
  assert.match(source, /VENDOR_FILTERS/);
  assert.match(source, /SORT_OPTIONS/);
  assert.match(source, /collection/);
  assert.match(source, /category/);
  assert.match(source, /vendor/);
  assert.match(source, /sort/);
  assert.match(source, /params\.set\('collection', collection\)/);
  assert.match(source, /params\.set\('category', category\)/);
  assert.match(source, /params\.set\('vendor', vendor\)/);
  assert.match(source, /params\.set\('sort', sort\)/);
  assert.match(source, /PRODUCT_VIEWS/);
  assert.match(source, /selectedProducts/);
  assert.match(source, /toggleProductSelection/);
  assert.match(source, /toggleAllProducts/);
  assert.match(source, /selectedProducts\.size/);
  assert.match(source, /More actions/);
  assert.match(source, /Export/);
  assert.match(source, /Import/);
  assert.match(source, /Product status/);
  assert.match(source, /Product organization/);
  assert.match(source, /Sales channels/);
  assert.match(source, /statusBadgeClass/);
  assert.match(source, /inventoryBadgeClass/);
  assert.match(source, /product-view-tabs/);
  assert.match(source, /product-filter-toolbar/);
  assert.match(source, /product-search-field/);
  assert.match(source, /SearchIcon/);
  assert.match(source, /Product filters/);
});

test('admin product editor exposes organization fields, variant price, and total inventory', async () => {
  const source = await readFile(path.join(import.meta.dirname, '..', 'src', 'admin', 'ProductEditor.jsx'), 'utf8');

  assert.match(source, /product-editor-shell/);
  assert.match(source, /product-editor-grid/);
  assert.match(source, /description-toolbar/);
  assert.match(source, /richStyleForCommand/);
  assert.match(source, /formatDescription/);
  assert.match(source, /Description toolbar/);
  assert.match(source, /contentEditable/);
  assert.match(source, /descriptionEditorRef/);
  assert.match(source, /syncDescriptionFromEditor/);
  assert.match(source, /applyRichDescriptionStyle/);
  assert.match(source, /Font style/);
  assert.match(source, /Font size/);
  assert.match(source, /Font color/);
  assert.match(source, /Font weight/);
  assert.match(source, /DESCRIPTION_FONT_STYLES/);
  assert.match(source, /DESCRIPTION_FONT_SIZES/);
  assert.match(source, /DESCRIPTION_COLORS/);
  assert.match(source, /DESCRIPTION_FONT_WEIGHTS/);
  assert.match(source, /Bold/);
  assert.match(source, /Italic/);
  assert.match(source, /Underline/);
  assert.match(source, /Heading/);
  assert.match(source, /Bullet list/);
  assert.match(source, /Link/);
  assert.match(source, /Media/);
  assert.match(source, /Add photos/);
  assert.match(source, /Remove photo/);
  assert.match(source, /Publishing/);
  assert.match(source, /Sales past 90 days/);
  assert.match(source, /category/);
  assert.match(source, /productType/);
  assert.match(source, /vendor/);
  assert.match(source, /tags/);
  assert.match(source, /themeTemplate/);
  assert.match(source, /Total inventory/);
  assert.match(source, /variantPricePeso/);
  assert.match(source, /priceCents:\s*pesoToCents\(variantPricePeso/);
});
