import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';

test('admin products page exposes phase 1 filters and sort controls', async () => {
  const source = await readFile(path.join(import.meta.dirname, '..', 'src', 'admin', 'Products.jsx'), 'utf8');

  assert.match(source, /COLLECTION_FILTERS/);
  assert.match(source, /CATEGORY_FILTERS/);
  assert.match(source, /VENDOR_FILTERS/);
  assert.match(source, /SORT_OPTIONS/);
  assert.match(source, /collection/);
  assert.match(source, /category/);
  assert.match(source, /vendor/);
  assert.match(source, /sort/);
  assert.match(source, /params\.set\('collection', collection\)/);
  assert.match(source, /params\.set\('category', category\)/);
  assert.match(source, /params\.set\('vendor', vendor\)/);
  assert.match(source, /params\.set\('sort', sort\)/);
  assert.match(source, /PRODUCT_VIEWS/);
  assert.match(source, /selectedProducts/);
  assert.match(source, /toggleProductSelection/);
  assert.match(source, /toggleAllProducts/);
  assert.match(source, /selectedProducts\.size/);
  assert.match(source, /More actions/);
  assert.match(source, /Export/);
  assert.match(source, /Import/);
  assert.match(source, /Product status/);
  assert.match(source, /Product organization/);
  assert.match(source, /Sales channels/);
  assert.match(source, /statusBadgeClass/);
  assert.match(source, /inventoryBadgeClass/);
  assert.match(source, /product-view-tabs/);
  assert.match(source, /product-filter-toolbar/);
  assert.match(source, /product-search-field/);
  assert.match(source, /SearchIcon/);
  assert.match(source, /Product filters/);
});

test('admin product editor exposes organization fields, variant price, and total inventory', async () => {
  const source = await readFile(path.join(import.meta.dirname, '..', 'src', 'admin', 'ProductEditor.jsx'), 'utf8');

  assert.match(source, /product-editor-shell/);
  assert.match(source, /product-editor-grid/);
  assert.match(source, /description-toolbar/);
  assert.match(source, /richStyleForCommand/);
  assert.match(source, /formatDescription/);
  assert.match(source, /Description toolbar/);
  assert.match(source, /contentEditable/);
  assert.match(source, /descriptionEditorRef/);
  assert.match(source, /syncDescriptionFromEditor/);
  assert.match(source, /applyRichDescriptionStyle/);
  assert.match(source, /Font style/);
  assert.match(source, /Font size/);
  assert.match(source, /Font color/);
  assert.match(source, /Font weight/);
  assert.match(source, /DESCRIPTION_FONT_STYLES/);
  assert.match(source, /DESCRIPTION_FONT_SIZES/);
  assert.match(source, /DESCRIPTION_COLORS/);
  assert.match(source, /DESCRIPTION_FONT_WEIGHTS/);
  assert.match(source, /Bold/);
  assert.match(source, /Italic/);
  assert.match(source, /Underline/);
  assert.match(source, /Heading/);
  assert.match(source, /Bullet list/);
  assert.match(source, /Link/);
  assert.match(source, /Media/);
  assert.match(source, /Add photos/);
  assert.match(source, /Remove photo/);
  assert.match(source, /Publishing/);
  assert.match(source, /Sales past 90 days/);
  assert.match(source, /category/);
  assert.match(source, /productType/);
  assert.match(source, /vendor/);
  assert.match(source, /tags/);
  assert.match(source, /themeTemplate/);
  assert.match(source, /Total inventory/);
  assert.match(source, /variantPricePeso/);
  assert.match(source, /priceCents:\s*pesoToCents\(variantPricePeso/);
  assert.match(source, /Product page content/);
  assert.match(source, /Product details/);
  assert.match(source, /Shipping/);
  assert.match(source, /Size Chart/);
  assert.match(source, /Width/);
  assert.match(source, /Length/);
  assert.match(source, /Sleeve length/);
  assert.match(source, /Shoulder drop length/);
  assert.match(source, /updateProductPage/);
  assert.match(source, /updateSizeChartRow/);
  assert.match(source, /addSizeChartRow/);
  assert.match(source, /removeSizeChartRow/);
  assert.match(source, /sizeChartRowIsComplete/);
  assert.match(source, /Complete every size chart field before saving/);
  assert.match(source, /queuedImages/);
  assert.match(source, /queueNewProductImages/);
  assert.match(source, /removeQueuedImage/);
  assert.match(source, /buildNewProductBody/);
  assert.match(source, /Add at least one product photo before saving/);
  assert.doesNotMatch(source, /Save this product before uploading photos/);
});

test('storefront product page renders editable product page content and size chart rows', async () => {
  const source = await readFile(path.join(import.meta.dirname, '..', 'src', 'pages', 'Product.jsx'), 'utf8');

  assert.match(source, /productPage\.detailsText/);
  assert.match(source, /productPage\.shippingText/);
  assert.match(source, /productPage\.sizeChart/);
  assert.match(source, /sizeChartRows/);
  assert.match(source, /Shoulder drop/);
  assert.match(source, /sleeveLength/);
  assert.match(source, /shoulderDropLength/);
  assert.match(source, /visibleSections/);
  assert.match(source, /sectionTitle === 'product details'/);
  assert.match(source, /sectionTitle !== 'shipping'/);
  assert.match(source, /sectionTitle !== 'size chart'/);
});
