import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';

test('product page keeps the purchase path prominent and secondary information collapsed', async () => {
  const source = await readFile(path.join(import.meta.dirname, '..', 'src', 'pages', 'Product.jsx'), 'utf8');

  assert.match(source, /aria-label="Previous product image"/);
  assert.match(source, /aria-label="Next product image"/);
  assert.match(source, /product-gallery-dot/);
  assert.match(source, /aria-label=\{`View product image \$\{index \+ 1\}`\}/);
  assert.match(source, /product-gallery-thumbnail/);
  assert.match(source, /scrollIntoView/);
  assert.match(source, /object-contain/);
  assert.match(source, /You May Also Like/);
  assert.match(source, /Add \{freeShippingMinimumItems\} or more item/);
  assert.match(source, /freeShippingEnabled/);
  assert.doesNotMatch(source, /activeDetailTab/);
  assert.match(source, /product-detail-accordion/);
  assert.match(source, /<summary className=/);
  assert.match(source, /title: 'Size Chart'/);
  assert.match(source, /View Size Chart/);
  assert.match(source, /sizeChartOpen/);
  assert.match(source, /aria-label="Size chart"/);
  assert.match(source, /loadedImageUrl === image\.url/);
  assert.match(source, /onLoad=\{\(\) => setLoadedImageUrl\(image\.url\)\}/);
  assert.doesNotMatch(source, /setMainImageLoaded\(false\)/);
  assert.match(source, /Cash on Delivery/);
  assert.doesNotMatch(source, /Secure online payment/);
  assert.match(source, /7-day replacement support/);
  assert.match(source, /Shipping fee is shown before you place the order/);
  assert.match(source, /displaySectionTitle/);
  assert.match(source, /min-h-11 min-w-11 rounded-full border/);
  assert.match(source, /rounded border border-line/);
  assert.match(source, /btn-ink customer-compact-button min-w-44 flex-1 !rounded/);
  assert.doesNotMatch(source, /border border-ink bg-white text-2xl/);
  assert.doesNotMatch(source, /aspect-\[4\/5\] overflow-hidden border border-line bg-white/);
  assert.match(source, /primaryDetailSections/);
  assert.match(source, /Size & fit/);
  assert.match(source, /Shipping & returns/);
  assert.match(source, /storefront-product-grid storefront-product-grid--mobile-two mt-8/);
});
