apiVersion: 1

datasources:
  - name: MariaClaraPostgres
    uid: maria-clara-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: postgres
    isDefault: true
    jsonData:
      database: maria_clara
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: $POSTGRES_PASSWORD
